---

- name: Setup DBServer
  hosts: dbsrvgrp
  become: yes
  tasks:
    - name: Install Postgresql server and acl
      apt:
        name:
          - postgresql
          - acl
        state: present
    - name: Install Python psycopg2
      apt:
        name: python3-psycopg2
        state: present
    - name: Start and Enable postgresql service
      service:
        name: postgresql
        state: started
        enabled: yes
    - name: Create a new database with name "accounts"
      become: true
      become_user: postgres
      postgresql_db:
        name: accounts
    - name: Connect to accounts database, create user, and grant access to database and table
      become_user: postgres    
      postgresql_user:
        db: accounts
        name: django
        password: ceec4eif7ya
        priv: "CONNECT/accounts:ALL"
        expires: "Jan 31 2025"
