---
- name: Setup WebServer
  hosts: websrvgrp
  become: yes
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present
    - name: Start and Enable apache2
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Deploy web file
      copy:
        src: index.html
        dest: /var/www/html/index.html

- name: Setup DBServer
  hosts: dbsrvgrp
  become: yes
  tasks:
    - name: Install Postgresql server
      apt:
        name: postgresql
        state: present
    - name: Start and Enable postgresql service
      service:
        name: postgresql
        state: started
        enabled: yes
